oms_shop:
    resource: "@OmsShopBundle/Controller/"
    type:     annotation
    prefix:   /

oms_base:
    resource: "@OmsBaseBundle/Controller/"
    type:     annotation
    prefix:   /

oms_user:
    resource: "@OmsUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# Redirect everything else to index, so ui-router can take over
root:
    path: /{rest}
    defaults:
        _controller: DsbaarsDemoBundle:Default:index
        path: /
